Weather
MallonsoFrey/ITGIRLS_Project3 pull request #2
Opened 2024-09-11 17:37 UTC by Alixess

add src & weather

2024-09-12 20:18 UTC, MallonsoFrey requested changes

2024-09-12 20:18 UTC, MallonsoFrey commented on index.html
> +    <link rel="stylesheet" href="./style.scss" />
Тут нужно убрать /, потом смогу сделать мердж:)

2024-09-13 08:00 UTC, Alixess commented on index.html
> +    <link rel="stylesheet" href="./style.scss" />
Из-за этого не дает сделать мердж? Очень странно, мне так преттиер выставляет

2024-09-13 08:53 UTC, MallonsoFrey approved these changes

2024-09-13 09:00 UTC, merged